default_popup: { width: "90%", height: "99%" }

scratches:
  nvim:
    command: ["nvim"]
    tmx_type: vim
    key: alt+i

  shell:
    shell: true
    tmx_type: sh
    tmux_mode: workspace
    tmux_prefix: ctrl+a
    key: alt+o

profiles:
  - name: laptop
    match: { max_client_width: 310 }
    popups:
      nvim: { width: "95%", height: "99%" }
      shell: { width: "95%", height: "99%" }

  - name: 2-3-ultrawide
    match: { max_client_width: 350 }
    popups:
      nvim: { width: "90%", height: "99%" }
      shell: { width: "90%", height: "99%" }

  - name: full-ultrawide
    match: { min_client_width: 400 }
    popups:
      nvim: { width: "70%", height: "99%" }
      shell: { width: "80%", height: "99%" }
